# Generated by Django 6.0.3 on 2026-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_community_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do GIF'),
        ),
        migrations.AddField(
            model_name='post',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do GIF'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conteúdo'),
        ),
    ]
