# Generated by Django 6.0.3 on 2026-04-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, choices=[('', 'Selecione seu curso'), ('automacao_industrial', 'Automação Industrial'), ('desenvolvimento_software_multiplataforma', 'Desenvolvimento de Software Multiplataforma'), ('fabricacao_mecanica', 'Fabricação Mecânica'), ('manutencao_industrial', 'Manutenção Industrial'), ('mecanica_processos_soldagem', 'Mecânica: Processos de Soldagem'), ('refrigeracao_ventilacao_ar_condicionado', 'Refrigeração, Ventilação e Ar Condicionado')], max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email institucional'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de perfil'),
        ),
    ]
