# Generated by Django 6.0.3 on 2026-04-28 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, choices=[('', 'Selecione seu curso'), ('Automação Industrial', 'Automação Industrial'), ('Desenvolvimento de Software Multiplataforma', 'Desenvolvimento de Software Multiplataforma'), ('Fabricação Mecânica', 'Fabricação Mecânica'), ('Manutenção Industrial', 'Manutenção Industrial'), ('Mecânica: Processos de Soldagem', 'Mecânica: Processos de Soldagem'), ('Refrigeração, Ventilação e Ar Condicionado', 'Refrigeração, Ventilação e Ar Condicionado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
